version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.8.1
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: specql-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
            key: specql-{{ cheksum "project.clj" }}
      - run: lein test
